In [2]:
import os
import cv2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tqdm import tqdm
import numpy as np
import imghdr
from PIL import Image
import shutil
from matplotlib import pyplot as plt

import tensorflow as tf
import pandas as pd
from random import shuffle
from matplotlib.pyplot import imread, imshow, subplots, show
%matplotlib inline
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [3]:
def show(img):
    try:
        cv2.imshow('img', img)
        cv2.waitKey(0)
    except:
        print('error')
        
def safe_mkdir(folder):
    assert not os.path.exists(folder)
    try:
        os.mkdir(folder)
    except OSError:
        print ("Создать директорию %s не удалось" % folder)
        
def to_grayscale(source_folder):
#     Принимает на вход папку, содержащую подпапки с изображениями, создаёт на том же уровне папку с добавлением к названию grayscale, внутри создаёт подпапки с изображениями
    assert os.path.exists(source_folder)
    output_folder = source_folder + ' grayscale'
    safe_mkdir(output_folder)
    for folder in tqdm(os.listdir(source_folder)):
        safe_mkdir(output_folder + '\\' + folder)
        for image in os.listdir(source_folder + '\\' + folder):
            img = cv2.imread(source_folder + '\\' + folder + '\\' + image, cv2.IMREAD_GRAYSCALE)
            image_path = source_folder + '\\' + folder + '\\' + image
            print(f'image: {image_path}, img: {img}')
            cv2.imwrite(output_folder + '\\' + folder + '\\' + image, img)
            
def to_grayscale_and_resize(source_folder, width, height):
#     Принимает на вход папку, содержащую подпапки с изображениями, создаёт на том же уровне папку с добавлением к названию _grayscale_resized, внутри создаёт подпапки с изображениями, сохраняя структуру подпапок
    assert os.path.exists(source_folder)
    output_folder = source_folder + '_grayscale_resized'
    safe_mkdir(output_folder)
    for folder in tqdm(os.listdir(source_folder)):
        safe_mkdir(output_folder + '\\' + folder)
        for image in os.listdir(source_folder + '\\' + folder):
            img = cv2.imread(source_folder + '\\' + folder + '\\' + image, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (width, height))
            cv2.imwrite(output_folder + '\\' + folder + '\\' + image, img)

In [77]:
# переименовываем все изображения в формат 000i.ext, ну просто для порядка
for folder in os.listdir(r'C:\Nikita\Parser\the whole 52 cards deck'):
    card_folder = 'C:\\Nikita\\Parser\\the whole 52 cards deck\\' + folder
    for i, file in enumerate(os.listdir(card_folder)):
        ext_len = file.rfind('.')
        ext = file[ext_len:]
        os.rename(card_folder + '\\' + file, card_folder + '\\' + str(i).zfill(4) + ext)

In [54]:
# проверяем, не затесались ли среди изображений гифки, а то cv2 с ними работать не умеет, трансформируем их в png
for folder in os.listdir(r'C:\Nikita\Parser\the whole 52 cards deck'):
    card_folder = 'C:\\Nikita\\Parser\\the whole 52 cards deck\\' + folder
    for file in os.listdir(card_folder):
        filetype = imghdr.what(card_folder + '\\' + file)
        if filetype == 'jpeg' or filetype == 'png':
            pass
        else:
            with Image.open(card_folder + '\\' + file) as img:
                ext_len = file.rfind('.')
                ext = file[ext_len:]
                new_filename = file[:ext_len] + '.png'
                img.save(card_folder + '\\' + new_filename)
            os.remove(card_folder + '\\' + file)
#             print(f'{card_folder}\\{file}: {filetype}')        

In [96]:
# проверяем, нет ли среди изображений файлов нулевого размера, или не являющихся изображениями вообще
for folder in os.listdir('C:\\Nikita\\Parser\\the whole 52 cards deck grayscale'):
    card_folder = 'C:\\Nikita\\Parser\\the whole 52 cards deck grayscale\\' + folder
    for file in os.listdir(card_folder):
        with Image.open(card_folder + '\\' + file) as img:
            print(f'{card_folder}\\{file}, size: {img.width}x{img.height}')
            if img.width == 0 or img.height == 0:
                print(f'0 size detected: {card_folder}\\{file}')

C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0000.jpg, size: 300x472
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0001.jpg, size: 350x540
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0002.jpg, size: 354x546
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0003.jpg, size: 370x560
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0004.jpg, size: 521x800
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0005.jpg, size: 1033x1396
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0006.jpg, size: 577x1024
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0007.jpg, size: 800x800
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0008.png, size: 700x700
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0009.png, size: 335x500
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0010.jpg, size: 667x760
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0011.jpg, size: 684x1024
C:\Nikita\Parser\the whole 52 cards deck grayscale\2C\0012.j

C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0005.jpg, size: 755x1110
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0006.png, size: 731x370
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0007.jpg, size: 1365x2048
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0008.jpg, size: 472x717
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0009.jpg, size: 709x1040
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0010.png, size: 700x700
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0011.jpg, size: 440x596
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0012.jpg, size: 900x1240
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0013.jpg, size: 425x623
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0014.jpg, size: 750x1106
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0015.png, size: 900x1024
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\0016.jpg, size: 111x150
C:\Nikita\Parser\the whole 52 cards deck grayscale\9C\001

C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0013.png, size: 800x1112
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0014.jpg, size: 511x720
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0015.jpg, size: 540x799
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0016.jpg, size: 666x1000
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0017.jpg, size: 667x1024
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0018.jpg, size: 515x800
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0019.jpg, size: 666x1000
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0020.jpg, size: 800x800
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0021.jpg, size: 802x1200
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0022.jpg, size: 666x1000
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0023.jpg, size: 602x880
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\0024.jpg, size: 649x1024
C:\Nikita\Parser\the whole 52 cards deck grayscale\QH\002

In [113]:
with Image.open('C:\\Nikita\\Parser\\the whole 52 cards deck grayscale test\\2C\\0000.jpg') as img:
#     plt.imshow(img)
    print(img.width, img.height)
type(img)

300 472


PIL.JpegImagePlugin.JpegImageFile

In [114]:
img = cv2.imread('C:\\Nikita\\Parser\\the whole 52 cards deck grayscale test\\2C\\0000.jpg')

In [116]:
img.shape

(472, 300, 3)

In [83]:
source_folder = r'C:\Nikita\Parser\the whole 52 cards deck'
to_grayscale(source_folder)

  2%|█▌                                                                                 | 1/52 [00:00<00:07,  7.15it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\2C\0000.jpg, img: [[236 232 228 ... 220 223 226]
 [141 137 133 ... 123 126 129]
 [115 110 105 ... 104 107 110]
 ...
 [116 102  96 ...  96  92 104]
 [114 106 100 ...  99  99 112]
 [126 125 119 ... 111 112 125]]
image: C:\Nikita\Parser\the whole 52 cards deck\2C\0001.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2C\0002.jpg, img: [[56 55 54 ... 57 58 58]
 [54 55 55 ... 59 60 60]
 [54 54 56 ... 61 62 62]
 ...
 [60 56 56 ... 59 62 63]
 [55 55 74 ... 61 61 63]
 [63 54 64 ... 58 61 63]]
image: C:\Nikita\Parser\the whole 52 cards deck\2C\0003.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\2C\0004.jpg, img: [[0 0 0 ..

  4%|███▏                                                                               | 2/52 [00:00<00:08,  5.88it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\2D\0003.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2D\0004.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2D\0005.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2D\0006.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


  6%|████▊                                                                              | 3/52 [00:00<00:08,  5.85it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\2H\0001.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\2H\0002.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\2H\0003.jpg, img: [[ 84  47  42 ...  30  35  62]
 [ 33   2   4 ...   2   7  34]
 [ 27   2   9 ...   0   1  28]
 ...
 [ 41  22   6 ...  11  27  46]
 [178 162 149 ... 147 158 173]
 [255 245 241 ... 242 246 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2H\0004.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\2H\0005.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 21

 10%|███████▉                                                                           | 5/52 [00:00<00:06,  6.74it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\2S\0005.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2S\0006.jpeg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2S\0007.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\2S\0008.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 ca

 12%|█████████▌                                                                         | 6/52 [00:00<00:06,  6.68it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\3D\0000.jpg, img: [[0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [4 1 0 ... 0 0 0]
 [3 1 0 ... 1 0 0]
 [0 0 2 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\3D\0001.jpg, img: [[144 144 144 ... 143 144 145]
 [143 143 143 ... 143 143 144]
 [142 143 143 ... 143 143 142]
 ...
 [143 143 143 ... 142 141 141]
 [143 143 143 ... 143 143 143]
 [143 143 143 ... 143 143 143]]
image: C:\Nikita\Parser\the whole 52 cards deck\3D\0002.jpg, img: [[250 251 251 ... 250 250 251]
 [251 251 251 ... 250 250 251]
 [251 251 251 ... 250 251 251]
 ...
 [252 252 252 ... 251 251 251]
 [253 253 252 ... 251 251 251]
 [253 253 252 ... 251 251 251]]
image: C:\Nikita\Parser\the whole 52 cards deck\3D\0003.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\3D\0004.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 .

 13%|███████████▏                                                                       | 7/52 [00:01<00:06,  7.40it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\3H\0018.jpg, img: [[254 255 253 ... 255 255 255]
 [253 255 255 ... 255 255 255]
 [255 253 252 ... 255 255 255]
 ...
 [255 255 254 ... 254 254 254]
 [253 253 253 ... 254 254 255]
 [254 254 254 ... 254 254 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\3H\0019.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [250 249 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\3H\0020.jpg, img: [[253 255 249 ... 255 255 254]
 [249 246 255 ... 251 255 253]
 [255 240 255 ... 250 255 250]
 ...
 [252 255 255 ... 254 254 254]
 [255 240 255 ... 253 253 253]
 [255 252 244 ... 253 253 253]]
image: C:\Nikita\Parser\the whole 52 cards deck\3H\0021.jpg, img: [[162 162 163 ... 222 222 222]
 [162 162 163 ... 223 223 223]
 [162 163 163 ... 223 223 223]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 17%|██████████████▎                                                                    | 9/52 [00:01<00:06,  7.03it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\3S\0008.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\4C\0000.jpg, img: [[29 28 32 ... 34 32 29]
 [33 35 40 ... 40 36 36]
 [30 37 44 ... 33 33 37]
 ...
 [28 28 31 ... 36 31 36]
 [26 27 30 ... 32 33 37]
 [30 29 28 ... 33 32 37]]
image: C:\Nikita\Parser\the whole 52 cards deck\4C\0001.jpg, img: [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\4C\0002.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\4C\0003.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 25

 19%|███████████████▊                                                                  | 10/52 [00:01<00:06,  6.03it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\4D\0002.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\4D\0003.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\4D\0004.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\4D\0005.jpg, img: [[253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 ...
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]


 23%|██████████████████▉                                                               | 12/52 [00:01<00:06,  5.81it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\4S\0000.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\4S\0001.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\4S\0002.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\4S\0003.jpg, img: [[254 254 254 ... 253 253 254]
 [254 254 254 ... 251 252 254]
 [254 254 254 ... 250 253 255]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\4S\0004.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 .

 25%|████████████████████▌                                                             | 13/52 [00:02<00:06,  6.42it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\5C\0007.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5C\0008.jpg, img: [[250 250 250 ... 255 253 252]
 [245 247 249 ... 254 253 251]
 [243 246 250 ... 254 253 251]
 ...
 [232 233 229 ... 253 253 253]
 [236 236 230 ... 254 253 252]
 [240 238 230 ... 254 254 252]]
image: C:\Nikita\Parser\the whole 52 cards deck\5C\0009.jpg, img: [[248 254 255 ... 250 251 245]
 [252 239 255 ... 250 253 255]
 [255 255 209 ... 224 251 255]
 ...
 [255 252 140 ... 197 242 245]
 [249 248 255 ... 255 249 255]
 [255 255 243 ... 248 249 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5C\0010.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]

 27%|██████████████████████                                                            | 14/52 [00:02<00:07,  5.19it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\5D\0011.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5D\0012.jpg, img: [[ 74  70  75 ...  60  75  67]
 [ 80  92 121 ...  99  92  61]
 [ 96 125 192 ... 222 180 111]
 ...
 [ 28   8  91 ...  71  77  60]
 [ 41  10  60 ...  75  90  91]
 [ 52  42  34 ... 118 125 100]]
image: C:\Nikita\Parser\the whole 52 cards deck\5D\0013.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]]
image: C:\Nikita\Parser\the whole 52 cards deck\5D\0014.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 29%|███████████████████████▋                                                          | 15/52 [00:02<00:07,  4.75it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\5H\0004.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5H\0005.jpg, img: [[253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 ...
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]]
image: C:\Nikita\Parser\the whole 52 cards deck\5H\0006.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5H\0007.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 31%|█████████████████████████▏                                                        | 16/52 [00:02<00:07,  4.70it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\5S\0004.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\5S\0005.jpg, img: [[68 68 68 ... 67 68 68]
 [68 68 68 ... 68 68 68]
 [68 68 68 ... 68 68 68]
 ...
 [68 68 68 ... 68 68 68]
 [68 68 68 ... 68 68 68]
 [68 68 68 ... 68 68 68]]
image: C:\Nikita\Parser\the whole 52 cards deck\5S\0006.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\5S\0007.jpg, img: [[255 255 248 ... 253 255 248]
 [255 240 255 ... 255 247 254]
 [249 253 255 ... 241 255 248]
 ...
 [251 255 255 ... 234 255 247]
 [255 244 252 ... 255 250 255]
 [255 254 255 ... 247 255 247]]
image: C:\Nikita\Parser\the whole 52 cards deck\5S\0008.jpg, img: [[255 255 

 35%|████████████████████████████▍                                                     | 18/52 [00:03<00:07,  4.67it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\6D\0000.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\6D\0001.jpg, img: [[1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 2 3 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\6D\0002.jpg, img: [[142 142 143 ... 144 143 142]
 [142 143 143 ... 144 143 143]
 [144 144 144 ... 143 143 143]
 ...
 [142 142 143 ... 143 143 142]
 [143 143 143 ... 143 143 143]
 [143 143 143 ... 143 143 143]]
image: C:\Nikita\Parser\the whole 52 cards deck\6D\0003.png, img: [[255 255 255 ... 238 238 239]
 [255 254 254 ... 237 237 238]
 [255 254 254 ... 237 237 238]
 ...
 [238 237 237 ... 254 254 255]
 [237 237 237 ... 254 254 254]
 [239 238 238 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 car

 37%|█████████████████████████████▉                                                    | 19/52 [00:03<00:06,  5.32it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\6H\0000.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\6H\0001.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\6H\0002.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\6H\0003.jpg, img: [[255 254 251 ... 255 255 255]
 [254 255 255 ... 253 253 251]
 [252 255 255 ... 251 255 255]
 ...
 [252 254 255 ... 254 255 255]
 [254 255 253 ... 255 253 253]


 38%|███████████████████████████████▌                                                  | 20/52 [00:03<00:07,  4.19it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\6S\0022.jpg, img: [[41 42 41 ... 39 41 46]
 [43 44 42 ... 40 39 43]
 [42 43 41 ... 43 44 47]
 ...
 [42 39 36 ... 40 43 45]
 [38 36 35 ... 41 44 46]
 [37 36 35 ... 48 43 46]]
image: C:\Nikita\Parser\the whole 52 cards deck\6S\0023.jpg, img: [[210 209 207 ... 208 209 209]
 [211 212 206 ... 210 209 209]
 [204 213 211 ... 212 209 209]
 ...
 [210 209 209 ... 207 208 207]
 [209 209 209 ... 206 209 209]
 [209 209 209 ... 210 209 209]]
image: C:\Nikita\Parser\the whole 52 cards deck\6S\0024.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0000.jpg, img: [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0001.jpg, img: [[145 143 

 40%|█████████████████████████████████                                                 | 21/52 [00:04<00:07,  4.12it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\7C\0012.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0013.jpg, img: [[250 248 255 ... 249 251 252]
 [252 248 253 ... 250 251 252]
 [253 248 252 ... 250 251 252]
 ...
 [251 251 251 ... 252 253 253]
 [251 251 251 ... 252 253 254]
 [251 251 251 ... 253 253 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0014.jpg, img: [[75 76 76 ... 75 76 76]
 [75 76 76 ... 75 76 76]
 [75 76 76 ... 75 76 76]
 ...
 [75 76 76 ... 75 76 76]
 [75 76 76 ... 75 76 76]
 [75 76 76 ... 75 76 76]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0015.jpg, img: [[3 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\7C\0016.jpg, img: [[255 255 

 42%|██████████████████████████████████▋                                               | 22/52 [00:04<00:06,  4.40it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\7D\0011.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7D\0012.jpg, img: [[45 44 43 ... 44 47 46]
 [43 42 42 ... 46 42 43]
 [42 41 40 ... 47 43 47]
 ...
 [42 42 42 ... 42 37 35]
 [40 41 43 ... 36 46 43]
 [42 44 46 ... 41 40 38]]
image: C:\Nikita\Parser\the whole 52 cards deck\7D\0013.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7H\0000.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\7H\0001.jpg, img: [[255 255

 44%|████████████████████████████████████▎                                             | 23/52 [00:04<00:06,  4.65it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\7H\0008.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7H\0009.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7H\0010.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\7S\0000.jpg, img: [[0 0 0 ... 0 1 2]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 2 1 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\7S\0001.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 5 0 0]
 [0 0 0 

 46%|█████████████████████████████████████▊                                            | 24/52 [00:04<00:06,  4.18it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\7S\0016.jpg, img: [[251 253 255 ... 253 253 253]
 [251 253 255 ... 253 253 253]
 [251 253 255 ... 253 253 253]
 ...
 [250 252 254 ... 252 252 253]
 [250 252 254 ... 252 252 253]
 [250 252 254 ... 252 252 253]]
image: C:\Nikita\Parser\the whole 52 cards deck\7S\0017.png, img: [[255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]
 ...
 [255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]]
image: C:\Nikita\Parser\the whole 52 cards deck\7S\0018.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\7S\0019.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 48%|███████████████████████████████████████▍                                          | 25/52 [00:04<00:06,  4.50it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\8C\0004.jpg, img: [[0 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 2 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8C\0005.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8C\0006.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8C\0007.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8C\0008.jpg, img: [[34 30 30 ... 13 13 11]
 [37 34 33 ... 31 25 16]
 [38 36 36 ... 55 41 24]
 ...
 [15 32 55 ... 76 54 30]
 [12 25 42 ... 53 41 29]
 [12 18 26 ... 34 26 11]]
image: C:\Nikita\Parser\the whole 

 50%|█████████████████████████████████████████                                         | 26/52 [00:04<00:05,  5.14it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\8D\0027.jpg, img: [[255 251 255 ... 255 239 215]
 [255 251 255 ... 255 234 212]
 [255 255 255 ... 255 240 218]
 ...
 [220 223 221 ... 232 241 251]
 [255 252 253 ... 243 236 228]
 [255 252 255 ... 255 236 215]]
image: C:\Nikita\Parser\the whole 52 cards deck\8D\0028.jpg, img: [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [51 50 49 ... 49 49 49]
 [51 49 48 ... 49 49 49]
 [48 49 49 ... 49 49 49]]
image: C:\Nikita\Parser\the whole 52 cards deck\8D\0029.jpg, img: [[254 254 254 ... 251 251 251]
 [254 254 254 ... 251 250 250]
 [254 254 254 ... 250 250 250]
 ...
 [ 50  50  51 ...  49  49  49]
 [ 50  50  51 ...  49  49  49]
 [ 50  50  51 ...  49  49  49]]
image: C:\Nikita\Parser\the whole 52 cards deck\8D\0030.jpg, img: [[ 50  50  51 ...  78  76  72]
 [ 53  53  54 ...  78  80  79]
 [ 57  58  58 ...  80  81  83]
 ...
 [123 121 120 ...  42  42  42]
 [123 121 120 ...  42  42  43]
 [122 121 119 ...  42  42  43]]
imag

 52%|██████████████████████████████████████████▌                                       | 27/52 [00:05<00:04,  5.54it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\8H\0011.png, img: [[255 255 255 ... 242 242 242]
 [255 255 255 ... 242 242 242]
 [255 255 255 ... 242 242 242]
 ...
 [242 242 242 ... 255 255 255]
 [242 242 242 ... 255 255 255]
 [242 242 242 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0000.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0001.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0002.jpg, img: [[47 42 42 ... 30 34 30]
 [51 48 46 ... 42 41 39]
 [49 49 47 ... 46 39 40]
 ...
 [40 38 36 ... 43 37 36]
 [42 43 37 ... 42 38 38]
 [36 40 36 ... 37 38 38]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0003.jpg, img: [[1 1 1 ..

 54%|████████████████████████████████████████████▏                                     | 28/52 [00:05<00:04,  4.97it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\8S\0019.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0020.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0021.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\8S\0022.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 car

 58%|███████████████████████████████████████████████▎                                  | 30/52 [00:05<00:03,  5.80it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\9C\0014.jpg, img: [[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [255 254 253 ... 254 254 254]
 [255 254 253 ... 254 254 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\9C\0015.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\9C\0016.jpg, img: [[235 255 235 ... 229 255 240]
 [255 134  21 ...  16 145 255]
 [224  19  37 ...  23  22 228]
 ...
 [231  29  22 ...  22  28 228]
 [255 150  29 ...  35 154 255]
 [249 255 225 ... 228 255 245]]
image: C:\Nikita\Parser\the whole 52 cards deck\9C\0017.jpg, img: [[41 42 49 ... 42 40 40]
 [49 48 48 ... 41 39 39]
 [45 46 43 ... 38 40 40]
 ...
 [53 51 51 ... 31 30 30]
 [57 56 56 ...  0  0  0]
 [18 18 17 ...  2  0  0]]
ima

 60%|████████████████████████████████████████████████▉                                 | 31/52 [00:05<00:03,  5.65it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\9H\0002.jpg, img: [[0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\9H\0003.jpg, img: [[252 252 252 ... 252 252 251]
 [252 252 252 ... 252 252 251]
 [252 252 252 ... 252 252 251]
 ...
 [252 252 251 ... 252 252 251]
 [252 252 251 ... 252 252 251]
 [252 252 251 ... 252 252 251]]
image: C:\Nikita\Parser\the whole 52 cards deck\9H\0004.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\9H\0005.jpg, img: [[255 255 254 ... 254 254 254]
 [255 255 254 ... 255 255 255]
 [255 255 254 ... 255 255 255]
 ...
 [255 255 255 ... 253 253 253]
 [255 255 255 ... 253 253 253]
 [255 255 255 ... 253 253 253]]
image: C:\Nikita\Parser\the whole 52 cards deck\9H\0006.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 .

 62%|██████████████████████████████████████████████████▍                               | 32/52 [00:06<00:04,  4.93it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\9S\0021.png, img: [[255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]
 [255 255 255 ... 231 231 231]
 ...
 [231 231 231 ... 255 255 255]
 [231 231 231 ... 255 255 255]
 [231 231 231 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\9S\0022.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0000.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0001.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0002.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 

 63%|████████████████████████████████████████████████████                              | 33/52 [00:06<00:05,  3.35it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\AC\0028.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0029.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0030.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AC\0031.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]


 65%|█████████████████████████████████████████████████████▌                            | 34/52 [00:07<00:05,  3.01it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\AD\0016.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AD\0017.jpg, img: [[250 240 125 ... 254 248 244]
 [250 237 155 ... 255 251 248]
 [252 227 183 ... 252 249 246]
 ...
 [251 250 175 ... 236 237 238]
 [252 253 184 ... 236 238 238]
 [253 246 158 ... 241 242 243]]
image: C:\Nikita\Parser\the whole 52 cards deck\AD\0018.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AD\0019.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 car

 67%|███████████████████████████████████████████████████████▏                          | 35/52 [00:07<00:06,  2.53it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\AH\0029.png, img: [[251 251 251 ... 237 237 237]
 [251 251 251 ... 237 237 237]
 [251 251 251 ... 237 237 237]
 ...
 [237 237 237 ... 251 251 251]
 [237 237 237 ... 251 251 251]
 [237 237 237 ... 251 251 251]]
image: C:\Nikita\Parser\the whole 52 cards deck\AH\0030.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AH\0031.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\AH\0032.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]

 69%|████████████████████████████████████████████████████████▊                         | 36/52 [00:07<00:05,  2.95it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\AS\0014.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\AS\0015.jpg, img: [[0 3 0 ... 1 1 1]
 [0 3 0 ... 2 0 0]
 [0 3 0 ... 0 2 2]
 ...
 [1 2 3 ... 0 0 0]
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 2 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\AS\0016.jpg, img: [[2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 ...
 [2 1 0 ... 5 1 1]
 [2 1 0 ... 1 1 1]
 [2 1 0 ... 0 1 1]]
image: C:\Nikita\Parser\the whole 52 cards deck\AS\0017.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\AS\0018.jpg, img: [[115 126 122 ... 116 121 119]
 [121 122 113 ...  91 111 123]
 [124 114 104 ...  87  93  98]
 ...
 [100  97 100 ... 1

image: C:\Nikita\Parser\the whole 52 cards deck\JC\0004.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0005.jpg, img: [[50 50 50 ... 43 43 46]
 [50 50 50 ... 46 49 49]
 [50 50 50 ... 44 40 30]
 ...
 [50 50 50 ... 50 50 50]
 [50 50 50 ... 50 50 50]
 [50 50 50 ... 50 50 50]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0006.jpg, img: [[251 251 252 ... 252 252 252]
 [251 252 252 ... 252 252 252]
 [252 252 252 ... 252 252 252]
 ...
 [252 252 252 ... 252 252 251]
 [252 252 252 ... 252 252 250]
 [252 252 252 ... 252 252 252]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0007.jpg, img: [[ 0  0  0 ... 10  1  0]
 [ 0  0  0 ... 10  1  0]
 [ 0  0  0 ... 10  1  0]
 ...
 [ 1  1  1 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]
 [ 1  1  1 ...  0  0  0]]
image: C:\Nikita\Parser\the whole 52 car

 71%|██████████████████████████████████████████████████████████▎                       | 37/52 [00:08<00:05,  2.74it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\JC\0013.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0014.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0015.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JC\0016.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 car

 73%|███████████████████████████████████████████████████████████▉                      | 38/52 [00:08<00:05,  2.54it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\JD\0011.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JD\0012.jpg, img: [[1 1 1 ... 1 1 2]
 [1 1 1 ... 2 3 3]
 [1 1 1 ... 3 4 5]
 ...
 [4 3 3 ... 1 1 1]
 [3 3 2 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
image: C:\Nikita\Parser\the whole 52 cards deck\JD\0013.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JD\0014.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\JD\0015.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 .

 75%|█████████████████████████████████████████████████████████████▌                    | 39/52 [00:09<00:05,  2.44it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\JH\0021.jpg, img: [[54 48 57 ... 43 43 43]
 [52 47 55 ... 44 45 45]
 [49 46 51 ... 45 46 46]
 ...
 [58 59 59 ... 58 60 60]
 [60 59 59 ... 59 59 59]
 [59 58 56 ... 59 57 57]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0000.png, img: [[200 200 200 ... 255 255 255]
 [200 200 200 ... 255 255 255]
 [200 200 200 ... 255 255 255]
 ...
 [200 200 255 ... 255 255 255]
 [200 200 255 ... 255 255 255]
 [200 200 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0001.jpg, img: [[ 8  0 10 ...  1  1  1]
 [17 22 30 ...  1  1  1]
 [58 67 55 ...  1  1  1]
 ...
 [18 17 17 ... 23 25 25]
 [18 18 19 ... 24 26 28]
 [17 19 21 ... 19 23 26]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0002.jpg, img: [[253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 [253 253 253 ... 253 253 253]
 ...
 [253 253 253 ... 252 252 253]
 [253 253 253 ... 252 253 254]
 [253 253 253 ... 255 245 246]]
image: C:\Nikita\Parser\the whole 52 car

 77%|███████████████████████████████████████████████████████████████                   | 40/52 [00:09<00:06,  1.85it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\JS\0035.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0036.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0037.png, img: [[255 255 255 ... 228 228 228]
 [255 255 255 ... 228 228 228]
 [255 255 255 ... 228 228 228]
 ...
 [255 255 255 ... 228 228 228]
 [255 255 255 ... 228 228 228]
 [255 255 255 ... 228 255 228]]
image: C:\Nikita\Parser\the whole 52 cards deck\JS\0038.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]


 79%|████████████████████████████████████████████████████████████████▋                 | 41/52 [00:10<00:05,  1.89it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\KC\0024.jpg, img: [[242 242 242 ... 242 242 242]
 [242 242 242 ... 242 242 242]
 [242 242 242 ... 242 242 242]
 ...
 [242 242 242 ... 242 242 242]
 [242 242 242 ... 242 242 242]
 [242 242 242 ... 242 242 242]]
image: C:\Nikita\Parser\the whole 52 cards deck\KC\0025.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [255 255 255 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\KC\0026.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KC\0027.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 81%|██████████████████████████████████████████████████████████████████▏               | 42/52 [00:10<00:04,  2.06it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\KD\0018.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KD\0019.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KD\0020.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KH\0000.jpg, img: [[ 7 16 23 ... 38 16 42]
 [18 14 14 ... 26 12 31]
 [ 2 13 33 ... 36 28 42]
 ...
 [45 15 53 ... 31 12  9]
 [39 62 31 ...  9  3 18]
 [48 41 35 ... 15 10 22]]
imag

 83%|███████████████████████████████████████████████████████████████████▊              | 43/52 [00:11<00:03,  2.25it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\KH\0010.jpg, img: [[255 255 255 ... 255 254 252]
 [255 255 255 ... 255 254 252]
 [255 255 255 ... 255 254 252]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KH\0011.jpg, img: [[255 255 255 ... 249 248 248]
 [255 255 255 ... 249 248 247]
 [255 255 255 ... 249 248 246]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KH\0012.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KH\0013.jpg, img: [[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 car

 85%|█████████████████████████████████████████████████████████████████████▍            | 44/52 [00:11<00:03,  2.14it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\KS\0024.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KS\0025.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [255 255 255 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\KS\0026.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\KS\0027.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]


 87%|██████████████████████████████████████████████████████████████████████▉           | 45/52 [00:12<00:02,  2.36it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\QC\0020.png, img: [[200 200 200 ... 255 255 255]
 [200 200 200 ... 255 255 255]
 [200 200 200 ... 255 255 255]
 ...
 [200 200 200 ... 255 255 255]
 [200 200 200 ... 255 255 255]
 [200 200 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QC\0021.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QC\0022.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\QD\0000.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 car

 88%|████████████████████████████████████████████████████████████████████████▌         | 46/52 [00:12<00:02,  2.09it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\QH\0000.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0001.jpg, img: [[29 30 31 ... 70 47 59]
 [30 30 31 ... 72 49 61]
 [31 32 32 ... 75 52 63]
 ...
 [29 30 32 ... 78 77 76]
 [31 32 33 ... 77 76 75]
 [ 0  0  0 ...  1  0  0]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0002.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0003.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [230 230 230 ... 230 230 230]
 [230 230 230 ... 230 230 230]
 [230 230 230 ... 230 230 230]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0004.jpg, img: [[0 0 0 ..

 90%|██████████████████████████████████████████████████████████████████████████        | 47/52 [00:13<00:02,  1.81it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\QH\0028.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0029.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0030.jpg, img: [[89 90 91 ... 93 93 93]
 [90 91 92 ... 93 93 93]
 [91 92 93 ... 93 93 93]
 ...
 [99 99 99 ... 96 96 96]
 [98 99 99 ... 96 96 96]
 [98 98 99 ... 96 96 96]]
image: C:\Nikita\Parser\the whole 52 cards deck\QH\0031.jpg, img: [[254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 ...
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [254 254 254 ... 254 254 254]]
ima

image: C:\Nikita\Parser\the whole 52 cards deck\QS\0036.jpg, img: [[255 255 255 ... 254 252 253]
 [255 255 255 ... 255 253 254]
 [255 255 255 ... 255 253 253]
 ...
 [255 255 255 ... 254 254 254]
 [254 254 254 ... 254 254 254]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QS\0037.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 254 254 253]
 [255 255 255 ... 254 253 251]
 [255 255 255 ... 254 254 253]]
image: C:\Nikita\Parser\the whole 52 cards deck\QS\0038.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QS\0039.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


 92%|███████████████████████████████████████████████████████████████████████████▋      | 48/52 [00:14<00:02,  1.53it/s]


image: C:\Nikita\Parser\the whole 52 cards deck\QS\0049.jpg, img: [[249 249 249 ... 252 252 253]
 [249 249 249 ... 252 252 253]
 [249 249 249 ... 252 252 253]
 ...
 [252 252 252 ... 254 254 254]
 [252 252 252 ... 254 254 254]
 [252 252 252 ... 254 254 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\QS\0050.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\QS\0051.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TC\0000.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 ca

 94%|█████████████████████████████████████████████████████████████████████████████▎    | 49/52 [00:14<00:01,  1.90it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\TC\0010.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TC\0011.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TC\0012.png, img: [[255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 [255 255 255 ... 230 230 230]
 ...
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]
 [230 230 230 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TC\0013.jpg, img: [[251 250 249 ... 251 251 251]
 [251 250 249 ... 250 250 250]
 [250 250 250 ... 250 250 250]
 ...
 [239 239 239 ... 239 238 241]
 [237 237 237 ... 239 239 241]


 96%|██████████████████████████████████████████████████████████████████████████████▊   | 50/52 [00:14<00:00,  2.29it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\TD\0008.jpg, img: [[252 248 245 ... 220 221 221]
 [253 254 255 ... 220 221 221]
 [246 254 255 ... 219 220 220]
 ...
 [253 253 253 ... 255 255 255]
 [253 253 253 ... 255 255 255]
 [253 253 253 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TD\0009.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\TD\0010.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TD\0011.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 car

 98%|████████████████████████████████████████████████████████████████████████████████▍ | 51/52 [00:14<00:00,  2.95it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\TS\0000.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0001.jpg, img: [[94 94 94 ... 94 94 94]
 [94 94 94 ... 94 94 94]
 [94 94 94 ... 94 94 94]
 ...
 [94 94 94 ... 94 94 94]
 [94 94 94 ... 94 94 94]
 [94 94 94 ... 94 94 94]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0002.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0003.png, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0004.jpg, img: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 

100%|██████████████████████████████████████████████████████████████████████████████████| 52/52 [00:15<00:00,  3.42it/s]

image: C:\Nikita\Parser\the whole 52 cards deck\TS\0017.png, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0018.jpg, img: [[ 75  77  77 ...  87  89  83]
 [ 77  79  79 ...  84  85  93]
 [ 78  80  80 ...  82  82 100]
 ...
 [ 81  80  79 ...  98 110 101]
 [ 80  81  82 ... 102 109 100]
 [ 79  83  87 ... 105 110 105]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0019.jpg, img: [[250 255 252 ... 253 255 251]
 [255 249 249 ... 255 255 247]
 [245 255 255 ... 243 255 251]
 ...
 [248 255 252 ... 237 255 250]
 [255 239 255 ... 255 252 253]
 [253 255 251 ... 252 250 254]]
image: C:\Nikita\Parser\the whole 52 cards deck\TS\0020.jpg, img: [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]


In [119]:
def augment_images(whole_deck_folder, number_of_images, width, height):
    '''
    функция принимает на вход папку whole_deck_folder, содержащую подпапки с изображениями карт, 
    создаёт на том же уровне папку с добавлением к названию "transformed" с подпапками, 
    имеющими те же имена, что в исходной папке, и помещает в подпапки оригинальные и трансформированные изображения, 
    общим числом около number_of_images для каждой игральной карты (подпапки)
    '''
    assert os.path.exists(whole_deck_folder)
    transformed_whole_deck_folder = whole_deck_folder + ' transformed'
    safe_mkdir(transformed_whole_deck_folder)
    
    for cardname in os.listdir(whole_deck_folder):
        card_folder = whole_deck_folder + '\\' + cardname
        folder = transformed_whole_deck_folder + '\\' + cardname
        safe_mkdir(folder)

        for i, image in tqdm(enumerate(os.listdir(card_folder))):
#             srcfile = card_folder + '\\' + image
#             dstfile = folder + '\\' + image
#             shutil.copy2(srcfile, dstfile)
            img = cv2.imread(card_folder + '\\' + image)
            img_resized = cv2.resize(img, (width, height))
#             img_to_write = img_resized.reshape(img_resized.shape[1], img_resized.shape[2], img_resized.shape[3])
            cv2.imwrite(folder + '\\' + image, img_resized)
            img = img.reshape(1, img.shape[0], img.shape[1], img.shape[2])
            data_generator = ImageDataGenerator(rotation_range=90, brightness_range=(0.5, 1.5), shear_range=15.0, zoom_range=[1.5, 1.5])
            data_generator.fit(img)
            image_iterator = data_generator.flow(img)
            X = number_of_images//len(os.listdir(card_folder)) # число аугментированных изображений выбираем таким образом, чтобы в итоге получилось около 1000 изображений каждой карты
            
            for x in range(X):
                img_transformed = image_iterator.next()
                img_transformed = img_transformed.reshape(img_transformed.shape[1], img_transformed.shape[2], img_transformed.shape[3])
                img_transformed = cv2.resize(img_transformed, (width, height))
                ext_len = image.rfind('.')
                filename = image[:ext_len] + str(i) + str(x) + image[ext_len:]
                cv2.imwrite(folder + '\\' + filename, img_transformed)

In [122]:
augment_images(r'C:\Nikita\Parser\the whole 52 cards deck grayscale', 1000, 180, 180)

17it [02:26,  8.64s/it]
18it [05:08, 17.11s/it]
13it [04:48, 22.23s/it]
10it [04:21, 26.13s/it]
11it [03:18, 18.02s/it]
13it [04:07, 19.05s/it]
55it [00:17,  3.16it/s]
9it [08:08, 54.30s/it]
13it [03:22, 15.61s/it]
11it [08:54, 48.55s/it]
12it [09:47, 48.97s/it]
12it [04:22, 21.91s/it]
12it [03:23, 16.92s/it]
17it [06:36, 23.30s/it]
14it [07:44, 33.15s/it]
13it [06:27, 29.77s/it]
17it [04:18, 15.19s/it]
16it [04:41, 17.62s/it]
12it [04:15, 21.29s/it]
25it [05:18, 12.72s/it]
20it [04:01, 12.07s/it]
14it [05:50, 25.04s/it]
11it [06:10, 33.69s/it]
26it [03:32,  8.17s/it]
20it [02:52,  8.64s/it]
63it [00:18,  3.44it/s]
12it [04:14, 21.24s/it]
25it [03:39,  8.79s/it]
18it [02:47,  9.29s/it]
13it [03:12, 14.77s/it]
16it [04:24, 16.50s/it]
23it [04:00, 10.44s/it]
39it [04:40,  7.20s/it]
29it [04:09,  8.59s/it]
35it [04:18,  7.38s/it]
63it [00:25,  2.43it/s]
18it [05:41, 18.98s/it]
23it [05:10, 13.49s/it]
22it [05:19, 14.52s/it]
48it [04:15,  5.33s/it]
30it [04:13,  8.45s/it]
21it [04:14, 12.1

In [126]:
dataset = []

folders = os.listdir('C:/Nikita/Parser/the whole 52 cards deck grayscale transformed')

for folder in folders:
    
    data=[]
    filepath = 'C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/' + folder
    print(filepath)
    assert os.path.exists(filepath)

    for img in tqdm(os.listdir(filepath)):

        label=folder
        img = cv2.imread(filepath+'/'+img, cv2.IMREAD_GRAYSCALE)
        # img = cv2.imread(filepath+'/'+img)
        # img = cv2.resize(img, (180, 180))
        imgs = img.reshape((1, img.shape[0], img.shape[1], 1))
        data.append([imgs, label])
    shuffle(data)

    dataset += data

np.save('C:/Nikita/Parser/data.npy', dataset)

 45%|██████████████████████████████████▋                                          | 452/1003 [00:00<00:00, 2171.45it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/2C


  6%|█████                                                                          | 64/1008 [00:00<00:02, 316.99it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/2D


  3%|██▌                                                                            | 33/1001 [00:00<00:02, 329.19it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/2H


  6%|████▋                                                                          | 60/1010 [00:00<00:03, 288.24it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/2S


  4%|███▍                                                                           | 43/1001 [00:00<00:02, 428.50it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/3C


  3%|██▎                                                                            | 29/1001 [00:00<00:03, 288.26it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/3D


  3%|██▎                                                                            | 30/1045 [00:00<00:03, 297.10it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/3H


  3%|██▋                                                                            | 34/1008 [00:00<00:02, 331.90it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/3S


  3%|██▌                                                                            | 32/1001 [00:00<00:03, 311.18it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/4C


  7%|█████▎                                                                         | 68/1001 [00:00<00:02, 334.12it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/4D


  8%|██████▎                                                                        | 80/1008 [00:00<00:02, 402.79it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/4H


  3%|██▌                                                                            | 32/1008 [00:00<00:03, 316.59it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/4S


  5%|███▊                                                                           | 48/1008 [00:00<00:02, 466.38it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/5C


  8%|██████▌                                                                        | 84/1003 [00:00<00:02, 426.25it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/5D


  3%|██▎                                                                            | 29/1008 [00:00<00:03, 283.71it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/5H


  4%|███▍                                                                           | 44/1001 [00:00<00:02, 434.14it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/5S


  5%|████▎                                                                          | 54/1003 [00:00<00:01, 533.78it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/6C


  6%|████▌                                                                          | 59/1008 [00:00<00:01, 588.50it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/6D


  6%|████▋                                                                          | 60/1008 [00:00<00:01, 597.60it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/6H


  9%|███████▎                                                                       | 95/1025 [00:00<00:01, 485.11it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/6S


 10%|███████▋                                                                      | 101/1020 [00:00<00:01, 511.27it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/7C


  5%|███▊                                                                           | 49/1008 [00:00<00:01, 486.70it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/7D


  4%|███▍                                                                           | 44/1001 [00:00<00:02, 434.88it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/7H


  3%|██▋                                                                            | 35/1014 [00:00<00:02, 344.26it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/7S


  4%|███▍                                                                           | 44/1020 [00:00<00:02, 431.78it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/8C


  6%|████▉                                                                          | 63/1008 [00:00<00:01, 625.58it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/8D


  4%|███▌                                                                           | 45/1008 [00:00<00:02, 440.76it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/8H


  4%|███▍                                                                           | 44/1025 [00:00<00:02, 435.27it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/8S


  5%|███▊                                                                           | 48/1008 [00:00<00:02, 473.18it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/9C


  5%|███▊                                                                           | 48/1001 [00:00<00:01, 479.92it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/9D


  8%|██████▌                                                                        | 83/1008 [00:00<00:02, 422.21it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/9H


 10%|███████▋                                                                       | 99/1012 [00:00<00:01, 494.30it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/9S


  9%|██████▉                                                                        | 89/1014 [00:00<00:02, 436.32it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/AC


  5%|███▋                                                                           | 48/1015 [00:00<00:02, 479.64it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/AD


  4%|███                                                                            | 40/1015 [00:00<00:02, 398.37it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/AH


  4%|██▉                                                                            | 37/1008 [00:00<00:02, 369.36it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/AS


  4%|███▎                                                                           | 42/1008 [00:00<00:02, 412.03it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/JC


  9%|███████                                                                        | 91/1012 [00:00<00:02, 458.06it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/JD


  4%|██▉                                                                            | 37/1012 [00:00<00:02, 363.66it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/JH


  4%|██▉                                                                            | 37/1008 [00:00<00:02, 365.09it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/JS


  8%|██████▍                                                                        | 83/1020 [00:00<00:02, 396.89it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/KC


  5%|███▊                                                                           | 49/1008 [00:00<00:01, 481.07it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/KD


  5%|███▋                                                                           | 48/1025 [00:00<00:02, 477.49it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/KH


 20%|███████████████▏                                                             | 202/1023 [00:00<00:00, 2001.21it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/KS


 42%|████████████████████████████████▍                                            | 426/1012 [00:00<00:00, 2110.22it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/QC


 21%|███████████████▉                                                             | 209/1008 [00:00<00:00, 2070.59it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/QD


 15%|███████████▏                                                                 | 149/1024 [00:00<00:00, 1476.13it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/QH


 18%|█████████████▉                                                               | 189/1040 [00:00<00:00, 1872.21it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/QS


 19%|██████████████▎                                                              | 188/1008 [00:00<00:00, 1862.35it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/TC


 44%|█████████████████████████████████▌                                           | 439/1008 [00:00<00:00, 2191.63it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/TD


 42%|████████████████████████████████▏                                            | 418/1001 [00:00<00:00, 2067.06it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/TH


 15%|███████████▌                                                                 | 152/1008 [00:00<00:00, 1493.05it/s]

C:/Nikita/Parser/the whole 52 cards deck grayscale transformed/TS


100%|█████████████████████████████████████████████████████████████████████████████| 1008/1008 [00:02<00:00, 494.85it/s]
C:\Users\administrator\anaconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [4]:
assert 'GPU' in tf.test.gpu_device_name() #run to make sure tensorflow is connected to gpu

In [5]:
data = np.load('C:/Nikita/Parser/data.npy', allow_pickle=True)

In [6]:
x = data[:, 0]
y = data[:, 1]

In [7]:
len(np.unique(y))

52

In [8]:
classes = np.unique(y)
numbers = list(range(len(classes)))
replacement_dict = dict(zip(classes, numbers))

for key in replacement_dict.keys():
    np.place(y, y == key, replacement_dict[key])
    
y = to_categorical(y)

In [9]:
x_new = []
for i in range (len(x)):
    x_new.append(np.array(x[i][0]))
    
x = np.array(x_new)
x.shape

(52569, 180, 180, 1)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, shuffle = True, random_state = 42)

In [11]:
for item in (x_train, y_train, x_test, y_test):
    print(item.shape)

(42055, 180, 180, 1)
(42055, 52)
(10514, 180, 180, 1)
(10514, 52)


In [12]:
tf.keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

epochs=25
batch_size=32

model = tf.keras.models.Sequential()

In [ ]:
# plt.imshow(x_train[2].reshape(180,180), cmap = 'Greys')

In [13]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(180, 180, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(512, activation='relu'),
  tf.keras.layers.Dense(52, activation='softmax')
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 178, 178, 64)      640       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 89, 89, 64)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 87, 87, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 43, 43, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 41, 41, 128)       73856     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 20, 20, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 18, 18, 128)      

In [15]:
cp = tf.keras.callbacks.ModelCheckpoint(filepath="C:/Nikita/Cards recognition/25epochs_conv.h5",
                               save_best_only=True,
                               verbose=0)

# model.compile(loss = 'sparse_categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [25]:
history = model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(x_test, y_test), callbacks=[cp]).history

Epoch 1/25
1315/1315 [==============================] - 51s 39ms/step - loss: 0.6122 - accuracy: 0.8877 - val_loss: 0.4483 - val_accuracy: 0.9148
Epoch 2/25
1315/1315 [==============================] - 51s 39ms/step - loss: 0.5973 - accuracy: 0.8852 - val_loss: 0.6890 - val_accuracy: 0.8917
Epoch 3/25
1315/1315 [==============================] - 52s 39ms/step - loss: 1.1670 - accuracy: 0.8820 - val_loss: 0.4331 - val_accuracy: 0.9425
Epoch 4/25
1315/1315 [==============================] - 52s 39ms/step - loss: 0.6747 - accuracy: 0.8856 - val_loss: 0.5108 - val_accuracy: 0.9271
Epoch 5/25
1315/1315 [==============================] - 52s 39ms/step - loss: 0.7195 - accuracy: 0.8728 - val_loss: 1.2982 - val_accuracy: 0.8884
Epoch 6/25
1315/1315 [==============================] - 52s 40ms/step - loss: 0.7215 - accuracy: 0.8780 - val_loss: 0.5226 - val_accuracy: 0.9211
Epoch 7/25
1315/1315 [==============================] - 52s 39ms/step - loss: 0.7183 - accuracy: 0.8767 - val_loss: 0.9669 -

In [2]:
from matplotlib import pyplot as plt
plt.plot(history['accuracy'], label = 'Accuracy')
plt.plot(history['val_accuracy'], label = 'Validation accuracy')
plt.legend()
plt.show()

NameError: name 'history' is not defined

In [ ]:
model.save('C:/Nikita/Cards recognition/model_52cards.h5')

In [24]:
img = cv2.imread('C:/Nikita/Playing cards/12.jpg', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (180, 180))

img.shape

test_card = img.reshape((1, img.shape[0], img.shape[1], 1))

# plt.imshow(test_card.reshape(180,180), cmap = 'Greys')

prediction = model.predict(test_card)
print(np.argmax(prediction), np.max(prediction))

36 0.27808857


In [298]:
prediction

array([[3.0829231e-08, 2.3873031e-07, 2.6982431e-07, 5.5213697e-17,
        9.0021873e-10, 3.7110545e-05, 7.0160513e-09, 1.6511022e-15,
        4.2992385e-04, 3.3545555e-10, 2.1047830e-11, 1.7927897e-13,
        1.1705093e-12, 4.8520275e-07, 3.8004509e-05, 5.6759442e-09,
        1.2944342e-06, 1.0021119e-02, 4.0849794e-05, 7.4397508e-07,
        1.1918572e-05, 1.2327678e-04, 1.3965407e-05, 1.0214587e-04,
        3.2465374e-03, 2.3038100e-02, 5.6448895e-03, 4.1780114e-04,
        6.7028836e-03, 2.4985094e-04, 9.5042764e-05, 4.8185620e-02,
        1.4066274e-08, 3.7417747e-04, 1.0346625e-05, 5.8126468e-03,
        1.8250122e-07, 5.6341948e-04, 2.4508580e-03, 6.5125879e-03,
        9.3335100e-04, 2.9850699e-04, 8.6371052e-01, 2.9067142e-04,
        3.8183671e-06, 1.7612318e-02, 8.4628660e-04, 9.7205426e-04,
        2.5017234e-04, 6.1939951e-05, 8.7869732e-04, 1.5339110e-05]],
      dtype=float32)

In [14]:
replacement_dict

{'2C': 0,
 '2D': 1,
 '2H': 2,
 '2S': 3,
 '3C': 4,
 '3D': 5,
 '3H': 6,
 '3S': 7,
 '4C': 8,
 '4D': 9,
 '4H': 10,
 '4S': 11,
 '5C': 12,
 '5D': 13,
 '5H': 14,
 '5S': 15,
 '6C': 16,
 '6D': 17,
 '6H': 18,
 '6S': 19,
 '7C': 20,
 '7D': 21,
 '7H': 22,
 '7S': 23,
 '8C': 24,
 '8D': 25,
 '8H': 26,
 '8S': 27,
 '9C': 28,
 '9D': 29,
 '9H': 30,
 '9S': 31,
 'AC': 32,
 'AD': 33,
 'AH': 34,
 'AS': 35,
 'JC': 36,
 'JD': 37,
 'JH': 38,
 'JS': 39,
 'KC': 40,
 'KD': 41,
 'KH': 42,
 'KS': 43,
 'QC': 44,
 'QD': 45,
 'QH': 46,
 'QS': 47,
 'TC': 48,
 'TD': 49,
 'TH': 50,
 'TS': 51}